name: TrickOrTreat
main: HBIDamian\TrickOrTreat\Main
version: 1.0.0
api: 5.0.0
author: HBIDamian
description: A fun plugin for Halloween!

commands:
  trickortreat:
    description: Trick or treat!
    usage: /trickortreat
    permission: trickortreat.command

permissions:
  trickortreat.command:
    description: Allows the player to trick or treat
    default: true
